jdbcUrl: jdbc:mysql://172.31.1.202:13306/hosp_datacenter_portal?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
jdbcUsername: root
jdbcPassword: key@123456
# 待生成表（支持多表，表名前后需加上单引号）
genTable: "'cms_service_info','cms_service_info_backup','cms_service_quota_backup','cms_service_scene_backup'"
# 代码包名
genPackage: com.chinacreator.hosp
# 代码作者
genAuthor: hc
# 表前缀
genPrefix: tb_
# 自动去除表前缀
genRemovePre: false