jdbcUrl: jdbc:mysql://106.55.62.135:3306/ry-vue?characterEncoding=utf8&useSSL=false
jdbcUsername: root
jdbcPassword: 123456
# 待生成表（支持多表，表名前后需加上单引号）
genTable: "'crf_event','crf_event_form_relation','crf_patient'"
# 代码包名
genPackage: com.chinacreator.hosp
# 代码作者
genAuthor: hc
# 表前缀
genPrefix: tb_
# 自动去除表前缀
genRemovePre: false